packages:
  - 'packages/*'
  - 'examples/*'
  - 'packs/*'
  - 'tools/*'

catalog:
  # Core Dependencies
  "@faker-js/faker": "^10.0.0"
  "@anthropic-ai/sdk": "^0.61.0"
  "zod": "^3.23.8"
  "zustand": "^4.5.2"
  "json-schema-faker": "^0.5.9"
  "msw": "^2.11.1"
  
  # Build Tools
  "tsup": "^8.5.0"
  "typescript": "^5.6.3"
  "vitest": "^2.1.5"
  
  # Node Types
  "@types/node": "^20.11.24"
  "@types/json-schema": "^7.0.15"
  "@types/react": "^18.3.1"
  "@types/react-dom": "^18.3.0"
  
  # Linting & Formatting
  "eslint": "^9.15.0"
  "@typescript-eslint/eslint-plugin": "^8.15.0"
  "@typescript-eslint/parser": "^8.15.0"
  "prettier": "^3.3.3"
  
  # React & Next.js
  "react": "^18.3.1"
  "react-dom": "^18.3.1"
  "next": "^14.2.32"
  
  # CSS & Styling
  "tailwindcss": "^3.4.17"
  "autoprefixer": "^10.4.20"
  "postcss": "^8.4.49"
